// src/js/constants/action-types.js

export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const MODIFY_CONTACT = "MODIFY_CONTACT";
export const UPDATE_CONTACTS = "UPDATE_CONTACTS";
export const CLEAR_CONTACTS = "CLEAR_CONTACTS";

export const REMOVE_USER_GROUPS = "REMOVE_USER_GROUPS";
export const MODIFY_USER_GROUPS = "MODIFY_USER_GROUPS";
export const UPDATE_USER_GROUPS = "UPDATE_USER_GROUPS";
export const CLEAR_USER_GROUPS = "CLEAR_USER_GROUPS";

export const USER_API_REQUEST = "USER_API_REQUEST";
export const USER_API_SUCCESS = "USER_API_SUCCESS";
export const USER_API_FAILURE = "USER_API_FAILURE";

export const GROUPS_API_REQUEST = "GROUPS_API_REQUEST";
export const GROUPS_API_SUCCESS = "GROUPS_API_SUCCESS";
export const GROUPS_API_FAILURE = "GROUPS_API_FAILURE";