// src/js/constants/action-types.js

export const ADD_CONTACT = "ADD_CONTACT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const MODIFY_CONTACT = "MODIFY_CONTACT";
export const CHANGE_SORTING = "CHANGE_SORTING";
export const CHANGE_SEARCH_FILTER = "CHANGE_SEARCH_FILTER";
export const ADD_SELECTED_ITEM = "ADD_SELECTED_ITEM";
export const REMOVE_SELECTED_ITEM = "REMOVE_SELECTED_ITEM";
export const CLEAR_SELECTED_ITEMS = "CLEAR_SELECTED_ITEMS";
export const CLEAR_CONTACTS = "CLEAR_CONTACTS";